### ISSUE TITLE
Bug: Strange behaviours of Giteabot when request a review of user

### ISSUE THREAD

**Issue by lunny** [GiteaBot/gitea-backporter#104]
<img width="577" alt="图片" src="https://github.com/GiteaBot/gitea-backporter/assets/81045/cac35ef5-c1b2-4621-91f5-025f46c61d2c">

ref https://github.com/go-gitea/gitea/pull/26729

**Comment by yardenshoham** [comment]
I don't see an issue, if @KN4CK3R is requested to review then we ignore his blocking review. Otherwise, his review is relevant and blocks the PR. This matches the icons in GitHub's widget. 

![image](https://github.com/GiteaBot/gitea-backporter/assets/20454870/e561fe17-c3a6-4f95-b547-f598b908fd16)

What behavior did you expect?

- Related https://github.com/GiteaBot/gitea-backporter/issues/74
- CC @silverwind

**Comment by KN4CK3R** [comment]
I think lunny talks about the added `lgtm/done` label in the last line. The review request should not have changed that because I still blocked the PR at that time.

**Comment by yardenshoham** [comment]
The feature request lists the opposite

![image](https://github.com/GiteaBot/gitea-backporter/assets/20454870/f81c7195-136f-4520-8995-e0a5792b71e2)

**Comment by KN4CK3R** [comment]
But I did not approve the changes previously, I requested changes. Therefore the status should always be blocked.

**Comment by silverwind** [comment]
I did notice the bot sometimes adding wrong `lgtm/done` while commenting on code too, so there is definitely some bug there. If the checkmark count is correct, I suspect it's a bug on GitHub's side because they should not have set the checkmark.

**Comment by yardenshoham** [comment]
Please decide what the desired behavior should be, and I will implement it.

**Comment by KN4CK3R** [comment]
But the re-request of a negative review does not clear the merge block on Github.

**Comment by KN4CK3R** [comment]
See this PR https://github.com/go-gitea/gitea/pull/25396
I blocked it and requested changes. My re-review is requested and the icon is yellow. Still the bottom shows that I block that PR at the moment:
![grafik](https://github.com/GiteaBot/gitea-backporter/assets/1666336/13959856-74a8-4ed9-aae1-eaf1b901f32e)

**Comment by yardenshoham** [comment]
- How about #105 then?
