### ISSUE TITLE
A new label to close an issue if there are 1 month no response after the label marked.

### ISSUE THREAD

**Issue by lunny** [GiteaBot/gitea-backporter#106]
The label could be named `close_if_no_feedback` or we can reuse `need_feedback`.

When an issue has a label `need_feedback` but there is no any comment one month after the label added. then close it automatically.

**Comment by yardenshoham** [comment]
We need a condition here. Would the following condition work:

Close all issues that have `status/needs-feedback` AND a month has passed since the last comment from the author AND the last comment is not by the author

**Comment by lunny** [comment]
> Close all issues that have `status/needs-feedback` AND a month has passed since the last comment from the author AND the last comment is not by the author

How about `Close all issues that have `status/needs-feedback` AND a month has passed since no new comment from anyone after the label created?`

**Comment by yardenshoham** [comment]
I will try to implement it

**Comment by yardenshoham** [comment]
I created #108 for this
