### ISSUE TITLE
Autoclose PRs with `pr/last-call` that have had this label for at least a week

### ISSUE THREAD

**Issue by delvh** [GiteaBot/gitea-backporter#116]
As per our CoC:
If you start a last call, and no one reviews the PR within a week, you can consider this polite refusal and your PR will be closed.
This definition is automateable, especially now that we have the corresponding label.

**Comment by yardenshoham** [comment]
How do you imagine the condition? There's no info on the GitHub API object for a PR that says when a label was added to a PR. We could check that a PR has `pr/last-call` and the `updated_at` field is two weeks or more in the past

**Comment by delvh** [comment]
Sounds good
