### ISSUE TITLE
No conflicts but can not send backports

### ISSUE THREAD

**Issue by yp05327** [GiteaBot/gitea-backporter#119]
<made a mistake, so the old comment was deleted, see the comment below>

**Comment by yp05327** [comment]
There are two PRs of mine:
https://github.com/go-gitea/gitea/pull/29190
https://github.com/go-gitea/gitea/pull/29173

**Comment by silverwind** [comment]
Sounds like duplicate of https://github.com/GiteaBot/gitea-backporter/issues/110.
