### ISSUE TITLE
Race condition while adding labels

### ISSUE THREAD

**Issue by silverwind** [GiteaBot/gitea-backporter#122]
Label additions are not atomic operations it seems:

<img width="881" alt="image" src="https://github.com/GiteaBot/gitea-backporter/assets/115237/ef84cb7e-38c2-4208-a97a-ee6f68f41540">

Example PR: https://github.com/go-gitea/gitea/pull/29856

**Comment by yardenshoham** [comment]
There's no `gitea-backporter` code running in the screenshot

**Comment by silverwind** [comment]
Ah, the bug is actually in `actions/labeler`.
