### ISSUE TITLE
Done tracking with multiple branches

### ISSUE THREAD

**Issue by silverwind** [GiteaBot/gitea-backporter#124]
I think the bot needs to track "done" status per target branch, in https://github.com/go-gitea/gitea/pull/30193, it opened a second port backport to 1.21 after we closed the first one. Maybe `backport/v1.21/done` labels, or search existing PRs to do it label-less.

**Comment by yardenshoham** [comment]
I agree

**Comment by silverwind** [comment]
Could likely be done by checking by existance of branch in the bot's repo:

- [`backport-29314-v1.21`](https://github.com/GiteaBot/gitea/tree/backport-29314-v1.21)

**Comment by yardenshoham** [comment]
https://github.com/GiteaBot/gitea-backporter/pull/125
