### ISSUE TITLE
Incorrect committer info in translation updates

### ISSUE THREAD

**Issue by silverwind** [GiteaBot/gitea-backporter#16]
Noticed this bug:

<img width="589" alt="image" src="https://user-images.githubusercontent.com/115237/226148280-74030b24-1138-4932-9044-a085bc59ee76.png">

The committer of the translation updates is always set to the author of the previous commit. Correctly, GiteaBot should be both the author and committer.

**Comment by jolheiser** [comment]
That isn't the backporter, it's the update locale drone cron job, more specifically the drone git push plugin.

https://github.com/appleboy/drone-git-push/issues/52 was the issue, there was also a fix merged, but it appears we are still experiencing the problem. 🙁

**Comment by silverwind** [comment]
Hmm ok, maybe we should rewrite this sometimes 😉

**Comment by silverwind** [comment]
Example of one of my autocommit jobs:

https://github.com/StylishThemes/GitHub-Dark/blob/acc658e1c019a1326a6596d93240b393e9f45db3/.github/workflows/regenerate.yml#L24-L32

**Comment by yardenshoham** [comment]
See https://github.com/go-gitea/gitea/issues/21485
