### ISSUE TITLE
Remove `reviewed/wait-merge` after merge

### ISSUE THREAD

**Issue by silverwind** [GiteaBot/gitea-backporter#26]
I know it's not the original purpose of the bot, but it would be useful if the bot would remove the label after any sucessful PR merge, even if the bot is not the author.

**Comment by silverwind** [comment]
Could be done directly after deleting branch (https://github.com/GiteaBot/gitea-backporter/issues/11).

**Comment by yardenshoham** [comment]
As you said, this codebase was originally designed only to do backports. I see how we've laid the foundations (listen to GitHub webhooks and interact with GitHub's API) to do more. I will implement this. Before we merge this we do have to get an opinion from a TOC member acknowledging the expansion of this codebase's scope.
