### ISSUE TITLE
[proposal] Assign milestone for PRs automatically

### ISSUE THREAD

**Issue by lunny** [GiteaBot/gitea-backporter#38]
When a PR is sent to the main branch, it should be assigned the max value of the milestones.
If a PR is sent to `release/v1.19`, it should be assigned the max value of 1.19.x milestones.

**Comment by yardenshoham** [comment]
Accepted, will send a PR by tomorrow

**Comment by yardenshoham** [comment]
Actually, I will need a bit of time to rewrite so we can listen to events other than `push`

**Comment by silverwind** [comment]
Should probably only handle PRs to still-supported branches, e.g. only the last two, `release/v1.20` and `release/v1.19` currently, no 1.18 and lower.

**Comment by lunny** [comment]
> Should probably only handle PRs to still-supported branches, e.g. only the last two, `release/v1.20` and `release/v1.19` currently, no 1.18 and lower.
> 
> @lunny we do only support last two, right? Or was it three?

We even sometimes have three but most time always two.

**Comment by silverwind** [comment]
I guess hardcode it to three than to avoid having to manually manage versions.

**Comment by lunny** [comment]
The robot can hardcode the two and ignore the third which I think it's acceptable.

**Comment by yardenshoham** [comment]
I'll do it after https://github.com/GiteaBot/gitea-backporter/pull/39 lands

**Comment by silverwind** [comment]
> The robot can hardcode the two and ignore the third which I think it's acceptable.

Actually I think we need no list of branches as only trusted users can set these labels and as long as the branch exists, it'll work.

**Comment by yardenshoham** [comment]
#44 for this
