### ISSUE TITLE
Double merge in quick succession

### ISSUE THREAD

**Issue by silverwind** [GiteaBot/gitea-backporter#54]
https://github.com/go-gitea/gitea/pull/22175

These were pretty much back-to-back:

<img width="779" alt="image" src="https://user-images.githubusercontent.com/115237/233834549-c9651285-0459-4ad0-bef9-df7f7b9c5fe7.png">

**Comment by yardenshoham** [comment]
Possibly because we trigger it on `push` and on pull_request labeling

**Comment by silverwind** [comment]
This was a bit of an odd case. I added a `.` comment to satisfy the lgtm bit, but then another PR was landed pretty much at the same time into master. I guess it was bad timing.

**Comment by yardenshoham** [comment]
So close?

**Comment by silverwind** [comment]
I guess. Let's see how it goes with new lgtm bot then.
