### ISSUE TITLE
Update merge queue

### ISSUE THREAD

**Issue by jolheiser** [GiteaBot/gitea-backporter#6]
As we merge PRs, this code could also update 2-3 of the next-in-line PRs to be merged that have `reviewed/wait-merge`.

It may also be beneficial to do this per-branch, so we update things targeting `main` as well as `release/v1.19` etc.

/cc @delvh

**Comment by delvh** [comment]
To recap the discussion @jolheiser and myself had already:
If we only update one, it is possible that the CI fails and manual interaction will be required.
If we update all, we will put a lot of unnecessary strain on the CI as it needs to run a lot of pipelines without any reason.
Thus, a compromise would be to use two to three PRs per branch.
I'm rather in favor of `3` as it allows for a higher CI error probability.

One thing we need to ensure is a consistent merge queue order for it to work correctly.

**Comment by jolheiser** [comment]
> One thing we need to ensure is a consistent merge queue order for it to work correctly.

I was thinking just a search query that orders them by index asc, so oldest PR is first in the queue. This could potentially be disrupted if an older PR is added to the queue, but I think it should be mostly consistent more often than not?
