### ISSUE TITLE
Support PR re-request / self-request review

### ISSUE THREAD

**Issue by silverwind** [GiteaBot/gitea-backporter#74]
Currently this is not possible using the GitHub REST API because re-requests or self-request after approval are not visible in the GitHub review REST API. I think the GraphQL API exposes these and we would have to use that API to correctly parse re-request.

**Comment by yardenshoham** [comment]
If user1 requests a review from user2 (user2 previously approved) is that the same as a dismissal of the approval? I don't think so

**Comment by silverwind** [comment]
I guess it would be rather rude to do that, but yes I think the final count should be a count of the checkmarks essentially.

**Comment by yardenshoham** [comment]
So we can implement that easily. A PR will be sent within the next 24 hours.
