### ISSUE TITLE
Better comment in case of backport failure

### ISSUE THREAD

**Issue by oliverpool** [GiteaBot/gitea-backporter#81]
Suggested in https://github.com/go-gitea/gitea/pull/24470#issuecomment-1543529961

Instead of the current message https://github.com/GiteaBot/gitea-backporter/blob/1437aadfbc556a97f8ad5af151fd14f82fda3803/src/backport.ts#L51

The bot could point to the `contrib/backport` tool (untested):
```ts
`I was unable to create a backport for ${giteaVersion.majorMinorVersion}. @${originalPr.user.login}, please send one manually. :tea:

\`\`\`
go run ./contrib/backport ${originalPr.number}
...  // fix git conflicts if any
go run ./contrib/backport --continue
\`\`\`
`
```

**Comment by yardenshoham** [comment]
@zeripath would this suggestion be correct?

**Comment by silverwind** [comment]
I haven't personally used that script, so I can't speak for it, but I guess I will try next time.

**Comment by zeripath** [comment]
I think it might be helpful to add the `--version` option to the first command but that is the intended use of the `--continue` option

**Comment by oliverpool** [comment]
Note: by _untested_, I meant that I didn't test the typescript code. Regarding the 2 bash commands, I actually used them for the mentioned PR (with the `--no-push` flag, since I prefer manually pushing)

**Comment by zeripath** [comment]
Glad it works for you @oliverpool nice to know that I've done it right

**Comment by yardenshoham** [comment]
PRs for this would be accepted
