### ISSUE TITLE
Direct users who add non-english translation changes to crowdin

### ISSUE THREAD

**Issue by techknowlogick** [GiteaBot/gitea-backporter#90]
Sometimes users (very kindly) add translations for other languages in their PR. We should add a gentle reminder to direct them to crowdin to let them know to contribute their changes there instead.

Maybe something like: "Hi, I noticed you've updated the locales for non-English languages. These will be overwritten during the sync from our translation tool Crowdin. If you'd like to contribute your translations, please visit https://crowdin.com/project/gitea."

**Comment by yardenshoham** [comment]
That sounds good, I'll try it when I get a chance

**Comment by yardenshoham** [comment]
PR created #91

**Comment by techknowlogick** [comment]
Thanks @yardenshoham 🙏
