### ISSUE TITLE
Lock issues closed for 3 months and pull requests merged/closed for 3 months automatically

### ISSUE THREAD

**Issue by lunny** [GiteaBot/gitea-backporter#96]
To avoid noise from the closed/merged issues/pull requests to ask users to create new issues, I think it's necessary to lock all old issues/pull requests.

**Comment by yardenshoham** [comment]
Created a PR

**Comment by silverwind** [comment]
Unforunately, the locking comment triggers a notification to users which I find annoying. Can we lock without comments?

**Comment by yardenshoham** [comment]
We only comment if the issue was updated in the past month

**Comment by yardenshoham** [comment]
Should I make it shorter than the past month?

**Comment by silverwind** [comment]
I see. I'm not sure, the less useless notifications, the better.

**Comment by yardenshoham** [comment]
Please reopen if you want a different behavior

**Comment by silverwind** [comment]
No comment at all would still be my preference, or a way to ignore these notifications, but GitHub does not offer a way unfortunately.

**Comment by yardenshoham** [comment]
But what if there is a discussion ongoing inside the closed issue? It will be rude to lock without comment

**Comment by silverwind** [comment]
Well, it's never clear what do to in such cases. Maybe reduce the period to 2 weeks.

**Comment by yardenshoham** [comment]
- #99

**Comment by silverwind** [comment]
Do you check last activity or last comment?

In https://github.com/go-gitea/gitea/pull/23947, last activity is 4 months ago, while last activity (label add) was 1 week ago. I think it should go by last comment.

**Comment by yardenshoham** [comment]
Last comment is another API call, should be doable

**Comment by yardenshoham** [comment]
#100 for that
